import { access, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const coreRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(coreRoot, "../..");
const manifest = JSON.parse(await readFile(resolve(coreRoot, "content-manifest.json"), "utf8"));
const seen = new Set();
const contentIdByPath = new Map(manifest.map((entry) => [resolve(repositoryRoot, entry.path), entry.id]));

function resolveContentLink(sourcePath, link) {
  const [pathname, suffix = ""] = link.split(/(?=[?#])/u, 2);
  const contentId = contentIdByPath.get(resolve(dirname(sourcePath), decodeURIComponent(pathname)));
  if (!contentId) throw new Error(`Unresolved Markdown link in ${sourcePath}: ${link}`);
  return `content://${contentId}${suffix}`;
}

function compileMarkdown(sourcePath, sourceMarkdown) {
  const assets = [];
  let markdown = sourceMarkdown.replace(/!\[([^\]]*)\]\(([^)]+)\)/gu, (_match, alt, rawPath) => {
    const decodedPath = decodeURIComponent(rawPath.replace(/'/gu, "%27"));
    const absolutePath = resolve(dirname(sourcePath), decodedPath);
    const id = relative(repositoryRoot, absolutePath).split(sep).join("/");
    const uri = `asset://${encodeURI(id).replace(/#/gu, "%23")}`;
    if (!assets.some((asset) => asset.id === id)) assets.push({ id, uri });
    return `![${alt}](${uri})`;
  });
  markdown = markdown.replace(/\]\(([^)]+\.md(?:[?#][^)]*)?)\)/gu, (_match, link) =>
    `](${resolveContentLink(sourcePath, link)})`);
  markdown = markdown.replace(/^(\[[^\]]+\]:)\s*(.+\.md(?:[?#].*)?)$/gmu, (_match, prefix, link) =>
    `${prefix}${resolveContentLink(sourcePath, link.trim())}`);
  return { markdown, assets };
}

const documents = await Promise.all(manifest.map(async (entry, index) => {
  if (seen.has(entry.id)) throw new Error(`Duplicate content id: ${entry.id}`);
  seen.add(entry.id);
  const sourcePath = resolve(repositoryRoot, entry.path);
  const sourceMarkdown = (await readFile(sourcePath, "utf8")).replace(/\r\n/gu, "\n");
  const { markdown, assets } = compileMarkdown(sourcePath, sourceMarkdown);
  await Promise.all(assets.map((asset) => access(resolve(repositoryRoot, asset.id))));
  const title = entry.title ?? /^#\s+(.+)$/m.exec(markdown)?.[1]?.trim();
  if (!title) throw new Error(`Missing H1 title: ${entry.path}`);
  return {
    ...entry,
    contentVersion: 1,
    title,
    previousId: manifest[index - 1]?.id,
    nextId: manifest[index + 1]?.id,
    markdown,
    assets,
  };
}));

const output = `// Generated by scripts/generate-content.mjs. Do not edit directly.\nexport const GENERATED_CONTENT = ${JSON.stringify(documents, null, 2)} as const;\n`;
const outputPath = resolve(coreRoot, "src/content/generated.ts");
const existingOutput = await readFile(outputPath, "utf8").catch(() => "");
if (existingOutput.replace(/\r\n/gu, "\n") !== output) {
  await writeFile(outputPath, output, "utf8");
}
